import jsPDF from 'jspdf';

interface Message {
    role: 'user' | 'assistant';
    content: string;
}

export function exportChatToPDF(
    messages: Message[],
    userName: string = 'User'
) {
    // Create new PDF document
    const doc = new jsPDF();

    // ---- HEADER ----
    doc.setFillColor(37, 99, 235); // blue color
    doc.rect(0, 0, 210, 30, 'F');

    doc.setTextColor(255, 255, 255); // white text
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Med-Genie Health Report', 105, 15, { align: 'center' });

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 105, 23, { align: 'center' });

    // ---- USER INFO ----
    doc.setTextColor(0, 0, 0); // black text
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`Patient: ${userName}`, 14, 45);

    // divider line
    doc.setDrawColor(37, 99, 235);
    doc.setLineWidth(0.5);
    doc.line(14, 50, 196, 50);

    // ---- CONVERSATION ----
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Conversation Summary', 14, 60);

    let yPosition = 70; // where to start writing

    messages.forEach((message) => {
        // Check if we need a new page
        if (yPosition > 250) {
            doc.addPage();
            yPosition = 20;
        }

        if (message.role === 'user') {
            // User message styling
            doc.setFillColor(219, 234, 254); // light blue background
            doc.setTextColor(30, 64, 175); // dark blue text
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(10);
            doc.text('You:', 14, yPosition);
        } else {
            // AI message styling  
            doc.setFillColor(240, 253, 244); // light green background
            doc.setTextColor(22, 101, 52); // dark green text
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(10);
            doc.text('Med-Genie:', 14, yPosition);
        }

        yPosition += 6;

        // Message content - wrap long text
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(9);

        const splitText = doc.splitTextToSize(message.content, 180);
        doc.text(splitText, 14, yPosition);
        yPosition += splitText.length * 5 + 8;
    });

    // ---- DISCLAIMER ----
    // Add new page if not enough space
    if (yPosition > 240) {
        doc.addPage();
        yPosition = 20;
    }

    // divider line before disclaimer
    doc.setDrawColor(200, 200, 200);
    doc.line(14, yPosition, 196, yPosition);
    yPosition += 8;

    doc.setFillColor(254, 243, 199); // yellow background
    doc.rect(14, yPosition, 182, 25, 'F');

    doc.setTextColor(146, 64, 14); // brown text
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('⚠️ Medical Disclaimer', 16, yPosition + 7);

    doc.setFont('helvetica', 'normal');
    doc.text(
        'This report is generated by Med-Genie AI and is for informational purposes only.',
        16, yPosition + 13
    );
    doc.text(
        'It is NOT a substitute for professional medical advice. Always consult a qualified doctor.',
        16, yPosition + 19
    );

    // ---- SAVE PDF ----
    doc.save(`MedGenie-Report-${new Date().toLocaleDateString().replace(/\//g, '-')}.pdf`);
}